// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlhSAArSgkPyP2Ih6tHqclxyBGCYkGcQw',
    appId: '1:274372341372:web:01ba90d5c1f16522e7a3f9',
    messagingSenderId: '274372341372',
    projectId: 'teniscondominio-6150f',
    authDomain: 'teniscondominio-6150f.firebaseapp.com',
    storageBucket: 'teniscondominio-6150f.firebasestorage.app',
    measurementId: 'G-KV8HEN6XCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG7dELScZegD2YXKGW7IvOHJZpzk386Nc',
    appId: '1:274372341372:android:21170d6f35a699bce7a3f9',
    messagingSenderId: '274372341372',
    projectId: 'teniscondominio-6150f',
    storageBucket: 'teniscondominio-6150f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6qS32At0ljxz2XR11XufrRg_ZA86ynLc',
    appId: '1:274372341372:ios:5d30b0cd77295b38e7a3f9',
    messagingSenderId: '274372341372',
    projectId: 'teniscondominio-6150f',
    storageBucket: 'teniscondominio-6150f.firebasestorage.app',
    iosBundleId: 'com.example.tenisCondominio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlhSAArSgkPyP2Ih6tHqclxyBGCYkGcQw',
    appId: '1:274372341372:web:2e85de8f1f5b37dce7a3f9',
    messagingSenderId: '274372341372',
    projectId: 'teniscondominio-6150f',
    authDomain: 'teniscondominio-6150f.firebaseapp.com',
    storageBucket: 'teniscondominio-6150f.firebasestorage.app',
    measurementId: 'G-NMXH0L2X23',
  );
}
